nampt/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/hello-world', 'HelloWorldController@show');

Route::resource('users','UsersController');

nampt/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

nampt/app/Http/Controllers/HelloWorldController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HelloWorldController extends Controller
{
   public function show()
   {
        return view('hello_world.show');
   }
}

nampt/app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

Use App\Model\Users;
use App\Http\Requests\CreateUsersRequest;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    protected $user;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct(Users $user)
    {
        $this->users = $user;
    }

    public function index(Request $request)
    {
        if ($request->has('search')) {
            $user = $this->users->searchUser($request);
            $i = ($user->currentpage()-1)* $user->perpage() + 1;
            return view('index', compact('user', 'i'));
        } else {
            $user = $this->users->getList();
            $i = ($user->currentpage()-1)* $user->perpage() + 1;
            return view('index', compact('user', 'i'));
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateUsersRequest $request)
    {   
        $createUser = $this->users->createUser($request->all());
        flash("Thêm người dùng mới thành công")->success()->important();
        return redirect()->route('users.index');
    }   

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

nampt/resources/views/create.blade.php
@extends('layouts.default');
@section('title','Create a User')
@section('content')
        <div class="container">
            <form method="POST" action="{{ url('users/') }}">
            {{csrf_field()}}
            <div class="row">
                <div class="col-md-4"></div>
                <div class="form-group col-md-4">
                    @if ($errors->has('mail_address'))
                    <label for="name" style="color: red">Mail_address:</label>
                    <input type="text" class="form-control" name="mail_address">
                    <div class="error" style="color: red">{{ $errors->first('mail_address') }}</div>
                    @else
                    <label for="name" >Mail_address:</label>
                    <input type="text" class="form-control" name="mail_address">
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-md-4"></div>
                <div class="form-group col-md-4">
                    @if ($errors->has('password'))
                    <label for="name" style="color: red">Password:</label>
                    <input type="password" style="border-color: red" class="form-control" name="password">
                    <div class="error" style="color: red">{{ $errors->first('password') }}</div>
                    @else
                    <label for="name">Password:</label>
                    <input type="password" class="form-control" name="password">
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-md-4"></div>
                <div class="form-group col-md-4">
                    @if ($errors->has('password'))
                    <label for="name" style="color: red">Password confirm:</label>
                    <input type="password" style="border-color: red" class="form-control" name="password_confirmation">
                    <div class="error" style="color: red">{{ $errors->first('password_confirmation') }}</div>
                    @else
                    <label for="name">Password confirm:</label>
                    <input type="password" class="form-control" name="password_confirmation">
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-md-4"></div>
                <div class="form-group col-md-4">
                    @if ($errors->has('name'))
                    <label for="name" style="color: red">Name:</label>
                    <input type="text" style="border-color: red" class="form-control" name="name">
                    <div class="error" style="color: red">{{ $errors->first('name') }}</div>
                    @else
                    <label for="name">Name:</label>
                    <input type="text" class="form-control" name="password_confirmation">
                    @endif
                </div>
            </div>
            <div class="row">
                <div class="col-md-4"></div>
                <div class="form-group col-md-4">
                    @if ($errors->has('address'))
                    <label for="name" style="color: red">Address:</label>
                    <input type="text" style="border-color: red" class="form-control" name="name">
                    <div class="error" style="color: red">{{ $errors->first('address') }}</div>
                    @else
                    <label for="address">Address:</label>
                    <input type="text" class="form-control" name="address">
                    @endif    
                    </div>
                </div>
            <div class="row">
                <div class="col-md-4"></div>
                <div class="form-group col-md-4">
                    @if ($errors->has('phone'))
                    <label for="name" style="color: red">Phone:</label>
                    <input type="text" style="border-color: red" class="form-control" name="phone">
                    <div class="error" style="color: red">{{ $errors->first('phone') }}</div>
                    @else
                    <label for="price">Phone:</label>
                    <input type="text" class="form-control" name="phone">
                    @endif
                </div>
            </div>
        </div>  
            </div>            
            <div class="row">
                <div class="col-md-4"></div>
                <div class="form-group col-md-4">
                <button type="submit" class="btn btn-success" style="margin-left:38px">Add Users</button>
              </div>
            </div>
            </form>
        </div>
@stop

nampt/resources/views/hello_world/show.blade.php
Hello My name is Phong Thanh Nam

nampt/resources/views/index.blade.php
<!-- index.blade.php -->

@extends('layouts.default');
@section('title','List User')
@section('content')
        <div class="container">
        <br />
        @include('flash::message')
        <form method="get" action="{{ route('users.index') }}">
            <div class="row col-md-3" >
                
                <div class="form-group" >
                    <label for="name" >Mail_address:</label>
                    <input type="text" class="form-control" name="mail_address">
                </div>
            </div>
            <div class="row col-md-3">
                
                <div class="form-group ">
                    <label for="name">Name:</label>
                    <input type="text" class="form-control" name="name">
                </div>
            </div>
            <div class="row col-md-3">
                
                <div class="form-group">
                    <label for="address">Address:</label>
                    <input type="text" class="form-control" name="address" value="" >   
                </div>
            </div>
            <div class="row col-md-3">
               
                <div class="form-group">
                    <label for="price">Phone:</label>
                    <input type="text" class="form-control" name="phone">
                </div>
            </div>
            <div class="row col-md-3>
                <div class="form-group col-md-4">
                    <label></label>
                    <div class="form-group col-md-1">
                    <button type="submit" name="search" class="btn btn-success" style="margin-left:38px" value="search" >Search</button>
                    </div>
                </div>    
            </div>
            </div>
            </div>            
        </form>
        </div>  
        <table class="table table-striped">
        <thead>
            <tr>
                <th style="text-align: center;">STT</th>
                <th style="text-align: center;">Địa chỉ email</th>
                <th style="text-align: center;">Tên</th>
                <th style="text-align: center;">Địa chỉ</th>
                <th style="text-align: center;">Số điện thoại</th>
            </tr>
        </thead>
        <tbody>
            @foreach($user as $users)
                <tr>
                    <td style="text-align: left;">{{ $i++ }}</td>
                    <td style="text-align: left;">{{ $users['mail_address'] }} </td>
                    <td style="text-align: left;">{{ ToUpperCase::toUpperCase($users->name) }}</td>
                    <td style="text-align: left;">{{ $users['address'] }}</td>
                    <td style="text-align: left;">{{ $users['phone'] }}</td>
                </tr>
            @endforeach
        </tbody>
        </table>
        {{ $user->links() }}
        <div class="row">
            <div class="col-md-4">  
                <a  class="btn btn-success"  href="{{ route('users.create') }} " style="text-decoration: none; color: white">Create User</a>
            </div>
        </div><br/>
        </div>
@stop

nampt/resources/views/layouts/default.blade.php
<!DOCTYPE html>
<html lang="en">
@include('layouts.head')
<body>
    @include('layouts.header')
    <div class="container">
        @yield('content')
    </div>
    @include('layouts.footer')
    <script src="//code.jquery.com/jquery.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <script>
    	$('#flash-overlay-modal').modal();
    </script>
</body>
</html>

nampt/resources/views/layouts/footer.blade.php
<div id="footer">
    <div class="container">
        <p align="center">PHP training by LIFETIME technologies</p>
    </div>
</div>

nampt/resources/views/layouts/head.blade.php
<head>
	<meta charset="utf-8">
    <title>Users Page</title>
    <link rel="stylesheet" href="{{asset('css/app.css')}}">
</head>

nampt/resources/views/layouts/header.blade.php
<p align="center"><font size="18">@yield('title')</font></p>

nampt/resources/views/layouts/index.blade.php
<!-- index.blade.php -->

@extends('layouts.default');
@section('title','List User')
@section('content')
        <div class="container">
        <br />
        @include('flash::message')
        <form method="get" action="{{ url('users/') }}">
            <div class="row col-md-3" >
                
                <div class="form-group" >
                    <label for="name" >Mail_address:</label>
                    <input type="text" class="form-control" name="mail_address">
                </div>
            </div>
            <div class="row col-md-3">
                
                <div class="form-group ">
                    <label for="name">Name:</label>
                    <input type="text" class="form-control" name="name">
                </div>
            </div>
            <div class="row col-md-3">
                
                <div class="form-group">
                    <label for="address">Address:</label>
                    <input type="text" class="form-control" name="address" value="" >   
                </div>
            </div>
            <div class="row col-md-3">
               
                <div class="form-group">
                    <label for="price">Phone:</label>
                    <input type="text" class="form-control" name="phone">
                </div>
            </div>
            <div class="row col-md-3>
                <div class="form-group col-md-4">
                    <label></label>
                    <div class="form-group col-md-1">
                    <button type="submit" name="search" class="btn btn-success" style="margin-left:38px" value="search" >Search</button>
                    </div>
                </div>    
            </div>
            </div>
            </div>            
        </form>
        </div>  
        <table class="table table-striped">
        <thead>
            <tr>
                <th style="text-align: center;">STT</th>
                <th style="text-align: center;">Địa chỉ email</th>
                <th style="text-align: center;">Tên</th>
                <th style="text-align: center;">Địa chỉ</th>
                <th style="text-align: center;">Số điện thoại</th>
            </tr>
        </thead>
        <tbody>
            @foreach($user as $users)
                <tr>
                    <td style="text-align: left;">{{ $i++ }}</td>
                    <td style="text-align: left;">{{ $users['mail_address'] }} </td>
                    <td style="text-align: left;">{{ ToUpperCase::toUpperCase($users->name) }}</td>
                    <td style="text-align: left;">{{ $users['address'] }}</td>
                    <td style="text-align: left;">{{ $users['phone'] }}</td>
                </tr>
            @endforeach
        </tbody>
        </table>
        {{ $user->links() }}
        <div class="row">
            <div class="col-md-4">  
                <a  class="btn btn-success"  href="{{ route('users.create') }} " style="text-decoration: none; color: white">Create User</a>
            </div>
        </div><br/>
        </div>
@stop